version: 2
updates:
  - package-ecosystem: maven
    directory: /
    schedule:
      interval: weekly
    groups:
      maven:
        patterns: ['*']
    commit-message:
      prefix: 'chore(deps)'

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    groups:
      actions:
        patterns: ['*']
    commit-message:
      prefix: 'ci(deps)'
